import type { Metadata } from "next";
import "@/styles/globals.css";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
      <head />
      <body className="bg-light">
      {children} {/* This renders the content of each page */}
      <Footer/>

      </body>
      </html>
  );
}

